---
- hosts: mygroup
  tasks:
  - name: Deploy flask setup service
    copy:
      src: /tmp/flask_setup.sh
      dest: /tmp/flask_setup.sh
      mode: '0755'
    
  - name: Run flask service
    shell: "/tmp/flask_setup.sh"
  
  - name: Deploy hello service
    copy:
      src: /tmp/hello.tar
      dest: /tmp/hello.tar
      mode: '0755'
      
  - name: Extract hello.tar into /var/www/hello
    unarchive:
      src: /tmp/hello.tar
      dest: /
      mode: '0775'
      
  - name: Deploy hello service
    copy:
      src: /var/www/hello/hello.service
      dest: /etc/systemd/system/hello.service
      remote_src: true
    notify:
      - restart hello service

  - name: Start hello
    service:
      name: hello
      state: started

  handlers:
  - name: restart hello service
    service:
      name: hello
      state: restarted
